CREATE TABLE IF NOT EXISTS `ShoppingCarts` (
  `CartName` varchar(75) NOT NULL,
  `CartType` varchar(50) NOT NULL,
  `CartID` varchar(50) NOT NULL,
  `URL` varchar(255) NOT NULL,
  `id` int(10) NOT NULL,
  `ServerID` varchar(50) NOT NULL,
  `CustomFunction` varchar(100) NOT NULL,
  `SynchInv` bit(1) NOT NULL,
  `Token` text NOT NULL,
  `ExpDate` DATETIME NOT NULL,
  `ImportTemplate` int(10) NOT NULL,
  `GlobalCartID` varchar(255) NOT NULL,
  `DKey` TEXT NOT NULL,
  `UseKey` bit(1) NOT NULL,
  `Password` varchar(255) NOT NULL,
  `ServerPwd` varchar(255) NOT NULL,
  `TimeStamp` timestamp NOT NULL,
  `CartSubType` varchar(255) NOT NULL,
  `created_at` TIMESTAMP,
  `updated_at` TIMESTAMP,
  PRIMARY KEY(`CartName`)
);

CREATE TABLE IF NOT EXISTS `Shippers` (
  `Code` varchar(100) NOT NULL,
  `Carrier` varchar(50) NOT NULL,
  `EmailTemplate` varchar(50) NOT NULL,
  `ButtonPrefix` varchar(250) NOT NULL,
  `ButtonSuffix` varchar(250) NOT NULL,
  `TimeStamp` timestamp NOT NULL,
  `created_at` TIMESTAMP,
  `updated_at` TIMESTAMP,
  PRIMARY KEY(`Code`)
);

CREATE TABLE IF NOT EXISTS `Tracking` (
  `OrderNum` varchar(50) NOT NULL,
  `AutoNumber` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `PickupDate` datetime not null,
  `Cost` varchar(25) NOT NULL,
  `Carrier` varchar(5) NOT NULL,
  `EmailSent` bit(1) NOT NULL,
  `StatusSent` bit(1) NOT NULL,
  `IsVoid` varchar(5) NOT NULL,
  `Notes` varchar(255) NOT NULL,
  `AZSent` bit(1) NOT NULL,
  `Pounds` int(10) NOT NULL,
  `Ounces` int(10) NOT NULL,
  `ShippersMethod` varchar(50) NOT NULL,
  `RegisteredMail` bit(1) NOT NULL,
  `InsuredMail` bit(1) NOT NULL,
  `CertifiedMail` bit(1) NOT NULL,
  `RestrictedDelivery` bit(1) NOT NULL,
  `CertificateOfMailing` bit(1) NOT NULL,
  `ReturnReceipt` bit(1) NOT NULL,
  `DeliveryConfirmation` bit(1) NOT NULL,
  `SignatureConfirmation` bit(1) NOT NULL,
  `COD` bit(1) NOT NULL,
  `FlatRate` bit(1) NOT NULL,
  `DazzleInsurance` varchar(20) NOT NULL,
  `CODAmount` FLOAT NOT NULL,
  `DeclaredValue` FLOAT NOT NULL,
  `Details` TEXT NOT NULL,
  `FlatBox` bit(1) NOT NULL,
  `DateAdded` datetime not null,
  `TrackingID` varchar(50) NOT NULL,
  `NumericKey` int(11) unsigned NOT NULL,
  `CostCurrencyType` varchar(3) NOT NULL,
  `ValueCurrencyType` varchar(3) NOT NULL,
  `External` bit(1) NOT NULL,
  `Packer` varchar(255) NOT NULL,
  `Picker` varchar(255) NOT NULL,
  `NumTrees` varchar(255) NOT NULL,
  `Length` varchar(255) NOT NULL,
  `Width` varchar(255) NOT NULL,
  `Height` varchar(255) NOT NULL,
  `BoxID` varchar(255) NOT NULL,
  `Location` varchar(255) NOT NULL,
  `TimeStamp` TIMESTAMP NOT NULL,
  `Status` varchar(100) NOT NULL,
  `UpdatedAt` datetime not null,
  `SignedBy` varchar(255) NOT NULL,
  `EstDeliveryDate` datetime not null,
  `created_at` TIMESTAMP,
  `updated_at` TIMESTAMP,
  PRIMARY KEY(`AutoNumber`)
);

CREATE TABLE IF NOT EXISTS `BoxTypes` (
  `BoxCode` varchar(10) NOT NULL,
  `Length` varchar(10) NOT NULL,
  `Width` varchar(10) NOT NULL,
  `Height` varchar(10) NOT NULL,
  `BoxCost` varchar(10) NOT NULL,
  `BoxID` varchar(10) NOT NULL,
  `SKU` varchar(10) NOT NULL,
  `created_at` TIMESTAMP,
  `updated_at` TIMESTAMP,
  PRIMARY KEY(`BoxCode`)
);

CREATE TABLE IF NOT EXISTS `Orders` (
  `OrderNumber` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `OrderSource` varchar(2) NOT NULL,
  `SourceOrderNumber` int(11) unsigned NOT NULL,
  `OrderDate` datetime not null,
  `OrderTime` datetime not null,
  `CustomerID` int(11) unsigned NOT NULL,
  `Name` varchar(255) NOT NULL,
  `Company` varchar(255) NOT NULL,
  `Email` varchar(255) NOT NULL,
  `Address` varchar(255) NOT NULL,
  `Address2` varchar(255) NOT NULL,
  `City` varchar(255) NOT NULL,
  `State` varchar(255) NOT NULL,
  `Country` varchar(255) NOT NULL,
  `Zip` varchar(255) NOT NULL,
  `Phone` varchar(255) NOT NULL,
  `ShipName` varchar(255) NOT NULL,
  `ShipCompany` varchar(255) NOT NULL,
  `ShipAddress` varchar(255) NOT NULL,
  `ShipAddress2` varchar(255) NOT NULL,
  `ShipCity` varchar(255) NOT NULL,
  `ShipState` varchar(255) NOT NULL,
  `ShipZip` varchar(255) NOT NULL,
  `ShipCountry` varchar(255) NOT NULL,
  `ShipPhone` varchar(255) NOT NULL,
  `PayType` int(10) NOT NULL,
  `pay1` varchar(255) NOT NULL,
  `pay2` varchar(255) NOT NULL,
  `pay3` varchar(255) NOT NULL,
  `pay4` varchar(255) NOT NULL,
  `CCInfo` varchar(250) NOT NULL,
  `ShipOn` varchar(255) NOT NULL,
  `OrderInst` TEXT NOT NULL,
  `Comments` TEXT NOT NULL,
  `ProductTotal` FLOAT NOT NULL,
  `TaxTotal` FLOAT NOT NULL,
  `ShippingTotal` FLOAT NOT NULL,
  `GrandTotal` FLOAT NOT NULL,
  `NumItems` int(10) NOT NULL,
  `Viewed` varchar(255) NOT NULL,
  `Shipping` varchar(255) NOT NULL,
  `Discount` FLOAT NOT NULL,
  `RevisedDiscount` FLOAT NOT NULL,
  `Coupon` varchar(50) NOT NULL,
  `CouponDiscount` FLOAT NOT NULL,
  `CouponOk` bit(1) NOT NULL,
  `Surcharge` FLOAT NOT NULL,
  `RevisedSurcharge` FLOAT NOT NULL,
  `RefName` varchar(50) NOT NULL,
  `GiftMessage` text NOT NULL,
  `Approved` bit(1) NOT NULL,
  `Cancelled` bit(1) NOT NULL,
  `FinalProductTotal` FLOAT NOT NULL,
  `FinalTaxTotal` FLOAT NOT NULL,
  `FinalShippingTotal` FLOAT NOT NULL,
  `FinalGrandTotal` FLOAT NOT NULL,
  `BalanceDue` FLOAT NOT NULL,
  `CreditIssued` bit(1) NOT NULL,
  `ReviewReason` varchar(50) NOT NULL,
  `BackOrdersToFill` bit(1) NOT NULL,
  `ShippedWeight` FLOAT NOT NULL,
  `FinalTaxRate` FLOAT NOT NULL,
  `Notes` TEXT NOT NULL,
  `RevisedCouponDiscount` FLOAT NOT NULL,
  `NoteToCustomer` TEXT NOT NULL,
  `DiscountsActive` bit(1) NOT NULL,
  `Taxable` bit(1) NOT NULL,
  `TaxNumber` varchar(50) NOT NULL,
  `ActualShippedWeight` FLOAT NOT NULL,
  `DiscountType` int(10) NOT NULL,
  `DiscountPercentage` int(10) NOT NULL,
  `SurchargeDetails` varchar(200) NOT NULL,
  `DropShipsAny` bit(1) NOT NULL,
  `DropShipsDone` bit(1) NOT NULL,
  `LocalSortText1` varchar(50) NOT NULL,
  `LocalSortText2` varchar(50) NOT NULL,
  `LocalSortText3` varchar(50) NOT NULL,
  `LocalSortText4` varchar(50) NOT NULL,
  `LocalSortText5` varchar(50) NOT NULL,
  `LocalSortInteger1` int(10) NOT NULL,
  `LocalSortInteger2` int(10) NOT NULL,
  `LocalSortInteger3` int(10) NOT NULL,
  `LocalSortInteger4` int(10) NOT NULL,
  `LocalSortInteger5` int(10) NOT NULL,
  `LocalSortDate1` datetime NOT NULL,
  `LocalSortDate2` datetime NOT NULL,
  `LocalSortDate3` datetime NOT NULL,
  `LocalSortDate4` datetime NOT NULL,
  `LocalSortDate5` datetime NOT NULL,
  `TaxByPOS` bit(1) NOT NULL,
  `DateCreated` datetime not null,
  `SourceOrderID` varchar(50) NOT NULL,
  `LocalSortCurrency1` float NOT NULL,
  `LocalSortCurrency2` float NOT NULL,
  `LocalSortCurrency3` float NOT NULL,
  `LocalSortCurrency4` float NOT NULL,
  `LocalSortCurrency5` float NOT NULL,
  `EmailCC` varchar(100) NOT NULL,
  `ImportID` int(10) NOT NULL,
  `AddToEmailList` bit(1) NOT NULL,
  `PaymentString` varchar(255) NOT NULL,
  `CustomerIP` varchar(255) NOT NULL,
  `OrderStatus` varchar(50) NOT NULL,
  `OrderStatusChanged` bit(1) NOT NULL,
  `OrdStatDetail` varchar(255) NOT NULL,
  `Exported` bit(1) NOT NULL,
  `CartID` int(10) NOT NULL,
  `created_at` TIMESTAMP,
  `updated_at` TIMESTAMP,
  PRIMARY KEY(`OrderNumber`)
);
